### ISSUE TITLE
lat e lon = NA

### ISSUE THREAD

**Issue by ramorimprojects** [th1460/CEP2COO#1]
Bom dia Thiago tudo bom?
Cara eu achei essa sua solução muito legal, porém ao adicionar o CEP está retornando NA na latitude e longitude... eu sou novo em R (e em programação em geral). Estou com um projeto onde vou precisar transformar 500mil CEPs em lat/long. Se puder me ajudar ficarei muito grato.

Abraços.

**Comment by th1460** [comment]
Olá, muito obrigado! geralmente o `NA` aparece porque o CEP é inexistente (ou faltam dígitos, etc). Você entrou somente com os números? Aqui mostro um exemplo de como utilizo a função: https://th1460.github.io/cep2coo.html. Qualquer coisa só falar!

**Comment by ramorimprojects** [comment]
Show!!! Consegui, estavam faltando algumas bibliotecas e agora está retornando certo a lat/long, só algumas que ele não encontrou, (mas aí acredito que é o OSM que não encontrou). Só falta eu criar uma rotina para ler meus 500mil registros! Muito obrigado pela ajuda =)

Abraços.
