### ISSUE TITLE
Versão do R

### ISSUE THREAD

**Issue by leandrofalmeida** [th1460/CEP2COO#2]
Fala Thiago blz? 
Cara estou iniciando em R, e uma dúvida de iniciante mesmo, todo esse codigo tem que ser executado no R Markdown para funcionar correto?

Outro detalhe, estou usando o R version 3.5.2 e pelo o que entendi o pacote photon não tem para esta versão, pelo menos é esta mensagem que fala no meu ambiente do R. Voce saberia orientar se existe uma outra opção?

Estou precisando fazer uma atividade justamente de transforma CEP em coordenada. 

Desde já obrigado pelo apoio

**Comment by th1460** [comment]
Caro @leandrofalmeida não é necessário rodar no `rmarkdown` para funcionar. Sobre o `photon` você deve baixá-lo deste repositório [aqui](https://github.com/rCarto/photon), utilizando `devtools::install_github(repo = 'rCarto/photon')`.
